<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BricksPlugin\Module'                                  => __DIR__ . '/Module.php',
    'Bricks\Plugin\ClassMapAutoloader'                     => __DIR__ . '/src/Bricks/Plugin/ClassMapAutoloader.php',
    'Bricks\Plugin\Extender\VisitorInterface'              => __DIR__ . '/src/Bricks/Plugin/Extender/VisitorInterface.php',
    'Bricks\Plugin\Extender'                               => __DIR__ . '/src/Bricks/Plugin/Extender.php',
    'Bricks\Plugin\Module'                                 => __DIR__ . '/src/Bricks/Plugin/Module.php',
    'Bricks\Plugin\PhpParser\Visitors\FileRefComment'      => __DIR__ . '/src/Bricks/Plugin/PhpParser/Visitors/FileRefComment.php',
    'Bricks\Plugin\PhpParser\Visitors\FileReferences'      => __DIR__ . '/src/Bricks/Plugin/PhpParser/Visitors/FileReferences.php',
    'Bricks\Plugin\Plugin'                                 => __DIR__ . '/src/Bricks/Plugin/Plugin.php',
    'Bricks\Plugin\ServiceManager\PluginFactory'           => __DIR__ . '/src/Bricks/Plugin/ServiceManager/PluginFactory.php',
    'Bricks\Plugin\StorageAdapter\FilesystemAdapter'       => __DIR__ . '/src/Bricks/Plugin/StorageAdapter/FilesystemAdapter.php',
    'Bricks\Plugin\StorageAdapter\StorageAdapterInterface' => __DIR__ . '/src/Bricks/Plugin/StorageAdapter/StorageAdapterInterface.php',
    'BricksPlugin\Plugin\Zend\Loader\ClassMapAutoloader'   => __DIR__ . '/src/BricksPlugin/Plugin/Zend/Loader/ClassMapAutoloader.php',
);
